-- ============================================================
-- 01_tablespaces.sql
-- Création des tablespaces — Nouvelle BDD GLPI Multi-Sites
-- Oracle XE
-- ============================================================

CREATE TABLESPACE TS_MATERIEL
    DATAFILE 'ts_materiel01.dbf'
    SIZE 100M AUTOEXTEND ON NEXT 50M MAXSIZE 1G
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_UTILISATEURS
    DATAFILE 'ts_utilisateurs01.dbf'
    SIZE 50M AUTOEXTEND ON NEXT 25M MAXSIZE 500M
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_RESEAU
    DATAFILE 'ts_reseau01.dbf'
    SIZE 100M AUTOEXTEND ON NEXT 50M MAXSIZE 1G
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_INDEX
    DATAFILE 'ts_index01.dbf'
    SIZE 100M AUTOEXTEND ON NEXT 50M MAXSIZE 1G
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO;

CREATE TEMPORARY TABLESPACE TS_TEMP_GLPI
    TEMPFILE 'ts_temp_glpi01.dbf'
    SIZE 50M AUTOEXTEND ON NEXT 25M MAXSIZE 500M
    EXTENT MANAGEMENT LOCAL
    UNIFORM SIZE 1M;
