-- ============================================================
-- 02_schema_tables.sql
-- Schema simplifie - BDD GLPI Multi-Sites
-- Oracle XE - 24 tables, FK explicites, tablespaces par domaine
-- ============================================================

-- =========================
-- TABLES TRANSVERSALES
-- =========================

CREATE TABLE entities (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(255) NOT NULL,
    entities_id     NUMBER,
    hier_level      NUMBER DEFAULT 1 NOT NULL,
    completename    VARCHAR2(1000),
    address         VARCHAR2(500),
    postcode        VARCHAR2(20),
    town            VARCHAR2(255),
    country         VARCHAR2(255),
    site_code       VARCHAR2(10) CHECK (site_code IN ('CERGY','PAU')),
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP
) TABLESPACE TS_MATERIEL;

ALTER TABLE entities ADD CONSTRAINT fk_entities_parent
    FOREIGN KEY (entities_id) REFERENCES entities(id);

CREATE TABLE locations (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities_id     NUMBER NOT NULL,
    name            VARCHAR2(255) NOT NULL,
    locations_id    NUMBER,
    hier_level      NUMBER DEFAULT 1,
    completename    VARCHAR2(1000),
    building        VARCHAR2(255),
    room            VARCHAR2(255),
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_loc_entity FOREIGN KEY (entities_id) REFERENCES entities(id)
) TABLESPACE TS_MATERIEL;

ALTER TABLE locations ADD CONSTRAINT fk_loc_parent
    FOREIGN KEY (locations_id) REFERENCES locations(id);

CREATE TABLE manufacturers (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(255) NOT NULL UNIQUE,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP
) TABLESPACE TS_MATERIEL;

CREATE TABLE states (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(255) NOT NULL UNIQUE,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP
) TABLESPACE TS_MATERIEL;

CREATE TABLE networks (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(255) NOT NULL UNIQUE,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP
) TABLESPACE TS_RESEAU;

CREATE TABLE asset_models (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category        VARCHAR2(50) NOT NULL
        CHECK (category IN ('COMPUTER','MONITOR','PERIPHERAL','PRINTER','PHONE','NETWORK_EQUIPMENT')),
    name            VARCHAR2(255) NOT NULL,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT uq_asset_model UNIQUE (category, name)
) TABLESPACE TS_MATERIEL;

-- =========================
-- UTILISATEURS ET DROITS
-- =========================

CREATE TABLE users (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login           VARCHAR2(255) NOT NULL UNIQUE,
    password        VARCHAR2(255),
    realname        VARCHAR2(255),
    firstname       VARCHAR2(255),
    phone           VARCHAR2(100),
    mobile          VARCHAR2(100),
    email           VARCHAR2(255),
    entities_id     NUMBER NOT NULL,
    locations_id    NUMBER,
    users_id_supervisor NUMBER,
    is_active       NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1)),
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_users_entity FOREIGN KEY (entities_id) REFERENCES entities(id),
    CONSTRAINT fk_users_loc FOREIGN KEY (locations_id) REFERENCES locations(id)
) TABLESPACE TS_UTILISATEURS;

ALTER TABLE users ADD CONSTRAINT fk_users_supervisor
    FOREIGN KEY (users_id_supervisor) REFERENCES users(id);

CREATE TABLE profiles (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(255) NOT NULL UNIQUE,
    interface       VARCHAR2(50) DEFAULT 'central',
    is_default      NUMBER(1) DEFAULT 0 CHECK (is_default IN (0, 1)),
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP
) TABLESPACE TS_UTILISATEURS;

CREATE TABLE profiles_users (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id        NUMBER NOT NULL,
    profiles_id     NUMBER NOT NULL,
    entities_id     NUMBER NOT NULL,
    is_recursive    NUMBER(1) DEFAULT 0 CHECK (is_recursive IN (0, 1)),
    CONSTRAINT fk_pu_user FOREIGN KEY (users_id) REFERENCES users(id),
    CONSTRAINT fk_pu_profile FOREIGN KEY (profiles_id) REFERENCES profiles(id),
    CONSTRAINT fk_pu_entity FOREIGN KEY (entities_id) REFERENCES entities(id),
    CONSTRAINT uq_profile_user_entity UNIQUE (users_id, profiles_id, entities_id)
) TABLESPACE TS_UTILISATEURS;

CREATE TABLE groups (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities_id     NUMBER NOT NULL,
    name            VARCHAR2(255) NOT NULL,
    groups_id       NUMBER,
    hier_level      NUMBER DEFAULT 1,
    completename    VARCHAR2(1000),
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_groups_entity FOREIGN KEY (entities_id) REFERENCES entities(id)
) TABLESPACE TS_UTILISATEURS;

ALTER TABLE groups ADD CONSTRAINT fk_groups_parent
    FOREIGN KEY (groups_id) REFERENCES groups(id);

CREATE TABLE groups_users (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id        NUMBER NOT NULL,
    groups_id       NUMBER NOT NULL,
    is_manager      NUMBER(1) DEFAULT 0 CHECK (is_manager IN (0, 1)),
    CONSTRAINT fk_gu_user FOREIGN KEY (users_id) REFERENCES users(id),
    CONSTRAINT fk_gu_group FOREIGN KEY (groups_id) REFERENCES groups(id),
    CONSTRAINT uq_group_user UNIQUE (users_id, groups_id)
) TABLESPACE TS_UTILISATEURS;

-- =========================
-- INVENTAIRE UNIFIE
-- =========================

CREATE TABLE assets (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities_id     NUMBER NOT NULL,
    category        VARCHAR2(50) NOT NULL
        CHECK (category IN ('COMPUTER','MONITOR','PERIPHERAL','PRINTER','PHONE','NETWORK_EQUIPMENT')),
    name            VARCHAR2(255) NOT NULL,
    serial          VARCHAR2(255),
    inventory_tag   VARCHAR2(255),
    uuid            VARCHAR2(255),
    users_id        NUMBER,
    users_id_tech   NUMBER,
    locations_id    NUMBER,
    asset_models_id NUMBER,
    manufacturers_id NUMBER,
    states_id       NUMBER,
    networks_id     NUMBER,
    notes           CLOB,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_assets_entity FOREIGN KEY (entities_id) REFERENCES entities(id),
    CONSTRAINT fk_assets_user FOREIGN KEY (users_id) REFERENCES users(id),
    CONSTRAINT fk_assets_tech FOREIGN KEY (users_id_tech) REFERENCES users(id),
    CONSTRAINT fk_assets_loc FOREIGN KEY (locations_id) REFERENCES locations(id),
    CONSTRAINT fk_assets_model FOREIGN KEY (asset_models_id) REFERENCES asset_models(id),
    CONSTRAINT fk_assets_manuf FOREIGN KEY (manufacturers_id) REFERENCES manufacturers(id),
    CONSTRAINT fk_assets_state FOREIGN KEY (states_id) REFERENCES states(id),
    CONSTRAINT fk_assets_net FOREIGN KEY (networks_id) REFERENCES networks(id),
    CONSTRAINT uq_assets_entity_serial UNIQUE (entities_id, serial)
) TABLESPACE TS_MATERIEL;

-- =========================
-- SUPPORT / TICKETS
-- =========================

CREATE TABLE ticket_categories (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(255) NOT NULL UNIQUE,
    description     VARCHAR2(1000),
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP
) TABLESPACE TS_SUPPORT;

CREATE TABLE tickets (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities_id     NUMBER NOT NULL,
    assets_id       NUMBER NOT NULL,
    title           VARCHAR2(255) NOT NULL,
    description     CLOB NOT NULL,
    status          VARCHAR2(30) DEFAULT 'NOUVEAU' NOT NULL
        CHECK (status IN ('NOUVEAU','ASSIGNE','EN_COURS','EN_ATTENTE','RESOLU','CLOS','ANNULE')),
    priority        VARCHAR2(20) DEFAULT 'MOYENNE' NOT NULL
        CHECK (priority IN ('BASSE','MOYENNE','HAUTE','CRITIQUE')),
    urgency         VARCHAR2(20) DEFAULT 'MOYENNE' NOT NULL
        CHECK (urgency IN ('BASSE','MOYENNE','HAUTE','CRITIQUE')),
    impact          VARCHAR2(20) DEFAULT 'MOYEN' NOT NULL
        CHECK (impact IN ('FAIBLE','MOYEN','ELEVE','MAJEUR')),
    requester_users_id NUMBER NOT NULL,
    assigned_groups_id NUMBER,
    ticket_categories_id NUMBER,
    resolution      CLOB,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_assigned   TIMESTAMP,
    date_resolved   TIMESTAMP,
    date_closed     TIMESTAMP,
    CONSTRAINT fk_ticket_entity FOREIGN KEY (entities_id) REFERENCES entities(id),
    CONSTRAINT fk_ticket_asset FOREIGN KEY (assets_id) REFERENCES assets(id) ON DELETE CASCADE,
    CONSTRAINT fk_ticket_requester FOREIGN KEY (requester_users_id) REFERENCES users(id),
    CONSTRAINT fk_ticket_assigned_group FOREIGN KEY (assigned_groups_id) REFERENCES groups(id),
    CONSTRAINT fk_ticket_category FOREIGN KEY (ticket_categories_id) REFERENCES ticket_categories(id)
) TABLESPACE TS_SUPPORT;

CREATE TABLE ticket_users (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tickets_id      NUMBER NOT NULL,
    users_id        NUMBER NOT NULL,
    role            VARCHAR2(30) DEFAULT 'TECHNICIEN' NOT NULL CHECK (role IN ('TECHNICIEN')),
    assigned_by     NUMBER,
    date_assigned   TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_tu_ticket FOREIGN KEY (tickets_id) REFERENCES tickets(id) ON DELETE CASCADE,
    CONSTRAINT fk_tu_user FOREIGN KEY (users_id) REFERENCES users(id),
    CONSTRAINT fk_tu_assigned_by FOREIGN KEY (assigned_by) REFERENCES users(id),
    CONSTRAINT uq_ticket_user UNIQUE (tickets_id, users_id)
) TABLESPACE TS_SUPPORT;

CREATE TABLE ticket_followups (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tickets_id      NUMBER NOT NULL,
    users_id        NUMBER NOT NULL,
    content         CLOB NOT NULL,
    is_private      NUMBER(1) DEFAULT 0 CHECK (is_private IN (0, 1)),
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_tf_ticket FOREIGN KEY (tickets_id) REFERENCES tickets(id) ON DELETE CASCADE,
    CONSTRAINT fk_tf_user FOREIGN KEY (users_id) REFERENCES users(id)
) TABLESPACE TS_SUPPORT;

-- =========================
-- RESEAU ESSENTIEL
-- =========================

CREATE TABLE network_ports (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities_id     NUMBER NOT NULL,
    assets_id       NUMBER NOT NULL,
    name            VARCHAR2(255),
    mac             VARCHAR2(50),
    port_type       VARCHAR2(100),
    logical_number  NUMBER DEFAULT 0,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_np_entity FOREIGN KEY (entities_id) REFERENCES entities(id),
    CONSTRAINT fk_np_asset FOREIGN KEY (assets_id) REFERENCES assets(id) ON DELETE CASCADE
) TABLESPACE TS_RESEAU;

CREATE TABLE network_connections (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_ports_id_1 NUMBER NOT NULL,
    network_ports_id_2 NUMBER NOT NULL,
    CONSTRAINT fk_nc_port1 FOREIGN KEY (network_ports_id_1) REFERENCES network_ports(id) ON DELETE CASCADE,
    CONSTRAINT fk_nc_port2 FOREIGN KEY (network_ports_id_2) REFERENCES network_ports(id) ON DELETE CASCADE,
    CONSTRAINT chk_nc_diff CHECK (network_ports_id_1 != network_ports_id_2)
) TABLESPACE TS_RESEAU;

CREATE TABLE vlans (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities_id     NUMBER NOT NULL,
    name            VARCHAR2(255) NOT NULL,
    tag             NUMBER NOT NULL,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_vlans_entity FOREIGN KEY (entities_id) REFERENCES entities(id),
    CONSTRAINT uq_vlan_tag UNIQUE (entities_id, tag)
) TABLESPACE TS_RESEAU;

CREATE TABLE network_port_vlans (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_ports_id NUMBER NOT NULL,
    vlans_id        NUMBER NOT NULL,
    tagged          NUMBER(1) DEFAULT 0 CHECK (tagged IN (0, 1)),
    CONSTRAINT fk_npv_port FOREIGN KEY (network_ports_id) REFERENCES network_ports(id) ON DELETE CASCADE,
    CONSTRAINT fk_npv_vlan FOREIGN KEY (vlans_id) REFERENCES vlans(id),
    CONSTRAINT uq_port_vlan UNIQUE (network_ports_id, vlans_id)
) TABLESPACE TS_RESEAU;

CREATE TABLE ip_networks (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities_id     NUMBER NOT NULL,
    vlans_id        NUMBER,
    name            VARCHAR2(255),
    address         VARCHAR2(40) NOT NULL,
    netmask         VARCHAR2(40) NOT NULL,
    gateway         VARCHAR2(40),
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_ipn_entity FOREIGN KEY (entities_id) REFERENCES entities(id),
    CONSTRAINT fk_ipn_vlan FOREIGN KEY (vlans_id) REFERENCES vlans(id)
) TABLESPACE TS_RESEAU;

CREATE TABLE ip_addresses (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities_id     NUMBER NOT NULL,
    network_ports_id NUMBER,
    ip_networks_id  NUMBER,
    address         VARCHAR2(40) NOT NULL,
    version         NUMBER(1) DEFAULT 4 CHECK (version IN (4, 6)),
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_ip_entity FOREIGN KEY (entities_id) REFERENCES entities(id),
    CONSTRAINT fk_ip_port FOREIGN KEY (network_ports_id) REFERENCES network_ports(id) ON DELETE SET NULL,
    CONSTRAINT fk_ip_network FOREIGN KEY (ip_networks_id) REFERENCES ip_networks(id)
) TABLESPACE TS_RESEAU;

-- =========================
-- TABLES SYSTEME
-- =========================

CREATE TABLE audit_log (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name      VARCHAR2(100) NOT NULL,
    record_id       NUMBER NOT NULL,
    action          VARCHAR2(10) NOT NULL CHECK (action IN ('INSERT','UPDATE','DELETE')),
    old_values      CLOB,
    new_values      CLOB,
    changed_by      VARCHAR2(100) DEFAULT USER,
    change_date     TIMESTAMP DEFAULT SYSTIMESTAMP
) TABLESPACE TS_MATERIEL;

CREATE TABLE archives_materiel (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_table    VARCHAR2(100) NOT NULL,
    source_id       NUMBER NOT NULL,
    data            CLOB NOT NULL,
    archived_by     VARCHAR2(100) DEFAULT USER,
    archive_date    TIMESTAMP DEFAULT SYSTIMESTAMP
) TABLESPACE TS_MATERIEL;
