-- ============================================================
-- 02_schema_tables.sql
-- Création des tables — Nouvelle BDD GLPI Multi-Sites
-- Oracle XE — FK explicites, contraintes, tablespaces
-- ============================================================

-- =========================
-- TABLES TRANSVERSALES
-- =========================

CREATE TABLE entities (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(255) NOT NULL,
    entities_id     NUMBER,
    hier_level      NUMBER DEFAULT 1 NOT NULL,
    completename    VARCHAR2(1000),
    address         VARCHAR2(500),
    postcode        VARCHAR2(20),
    town            VARCHAR2(255),
    country         VARCHAR2(255),
    site_code       VARCHAR2(10) CHECK (site_code IN ('CERGY','PAU')),
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP
) TABLESPACE TS_MATERIEL;

ALTER TABLE entities ADD CONSTRAINT fk_entities_parent
    FOREIGN KEY (entities_id) REFERENCES entities(id);

CREATE TABLE locations (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities_id     NUMBER NOT NULL,
    name            VARCHAR2(255) NOT NULL,
    locations_id    NUMBER,
    hier_level      NUMBER DEFAULT 1,
    completename    VARCHAR2(1000),
    building        VARCHAR2(255),
    room            VARCHAR2(255),
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_loc_entity FOREIGN KEY (entities_id) REFERENCES entities(id)
) TABLESPACE TS_MATERIEL;

ALTER TABLE locations ADD CONSTRAINT fk_loc_parent
    FOREIGN KEY (locations_id) REFERENCES locations(id);

CREATE TABLE manufacturers (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(255) NOT NULL UNIQUE,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP
) TABLESPACE TS_MATERIEL;

CREATE TABLE states (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities_id     NUMBER,
    name            VARCHAR2(255) NOT NULL,
    is_visible_computer       NUMBER(1) DEFAULT 1,
    is_visible_monitor        NUMBER(1) DEFAULT 1,
    is_visible_printer        NUMBER(1) DEFAULT 1,
    is_visible_phone          NUMBER(1) DEFAULT 1,
    is_visible_peripheral     NUMBER(1) DEFAULT 1,
    is_visible_networkequip   NUMBER(1) DEFAULT 1,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_states_entity FOREIGN KEY (entities_id) REFERENCES entities(id)
) TABLESPACE TS_MATERIEL;

CREATE TABLE networks (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(255) NOT NULL UNIQUE,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP
) TABLESPACE TS_MATERIEL;

-- Tables de types et modèles consolidées (résout le problème de redondance GLPI)
CREATE TABLE asset_types (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category        VARCHAR2(50) NOT NULL
        CHECK (category IN ('COMPUTER','MONITOR','PERIPHERAL','PRINTER','PHONE','NETWORK_EQUIPMENT')),
    name            VARCHAR2(255) NOT NULL,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT uq_asset_type UNIQUE (category, name)
) TABLESPACE TS_MATERIEL;

CREATE TABLE asset_models (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category        VARCHAR2(50) NOT NULL
        CHECK (category IN ('COMPUTER','MONITOR','PERIPHERAL','PRINTER','PHONE','NETWORK_EQUIPMENT')),
    name            VARCHAR2(255) NOT NULL,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT uq_asset_model UNIQUE (category, name)
) TABLESPACE TS_MATERIEL;

-- =========================
-- TABLES UTILISATEURS
-- =========================

CREATE TABLE user_titles (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(255) NOT NULL UNIQUE
) TABLESPACE TS_UTILISATEURS;

CREATE TABLE user_categories (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(255) NOT NULL UNIQUE
) TABLESPACE TS_UTILISATEURS;

CREATE TABLE users (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(255) NOT NULL UNIQUE,
    password        VARCHAR2(255),
    realname        VARCHAR2(255),
    firstname       VARCHAR2(255),
    phone           VARCHAR2(100),
    mobile          VARCHAR2(100),
    email           VARCHAR2(255),
    entities_id     NUMBER NOT NULL,
    locations_id    NUMBER,
    user_titles_id  NUMBER,
    user_categories_id NUMBER,
    users_id_supervisor NUMBER,
    is_active       NUMBER(1) DEFAULT 1,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_users_entity FOREIGN KEY (entities_id) REFERENCES entities(id),
    CONSTRAINT fk_users_loc FOREIGN KEY (locations_id) REFERENCES locations(id),
    CONSTRAINT fk_users_title FOREIGN KEY (user_titles_id) REFERENCES user_titles(id),
    CONSTRAINT fk_users_cat FOREIGN KEY (user_categories_id) REFERENCES user_categories(id)
) TABLESPACE TS_UTILISATEURS;

ALTER TABLE users ADD CONSTRAINT fk_users_supervisor
    FOREIGN KEY (users_id_supervisor) REFERENCES users(id);

CREATE TABLE profiles (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(255) NOT NULL UNIQUE,
    interface       VARCHAR2(50) DEFAULT 'central',
    is_default      NUMBER(1) DEFAULT 0,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP
) TABLESPACE TS_UTILISATEURS;

CREATE TABLE profile_rights (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profiles_id     NUMBER NOT NULL,
    name            VARCHAR2(255) NOT NULL,
    rights          NUMBER DEFAULT 0,
    CONSTRAINT fk_pr_profile FOREIGN KEY (profiles_id) REFERENCES profiles(id),
    CONSTRAINT uq_profile_right UNIQUE (profiles_id, name)
) TABLESPACE TS_UTILISATEURS;

CREATE TABLE profiles_users (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id        NUMBER NOT NULL,
    profiles_id     NUMBER NOT NULL,
    entities_id     NUMBER NOT NULL,
    is_recursive    NUMBER(1) DEFAULT 0,
    CONSTRAINT fk_pu_user FOREIGN KEY (users_id) REFERENCES users(id),
    CONSTRAINT fk_pu_profile FOREIGN KEY (profiles_id) REFERENCES profiles(id),
    CONSTRAINT fk_pu_entity FOREIGN KEY (entities_id) REFERENCES entities(id)
) TABLESPACE TS_UTILISATEURS;

CREATE TABLE groups (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities_id     NUMBER NOT NULL,
    name            VARCHAR2(255) NOT NULL,
    groups_id       NUMBER,
    hier_level      NUMBER DEFAULT 1,
    completename    VARCHAR2(1000),
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_groups_entity FOREIGN KEY (entities_id) REFERENCES entities(id)
) TABLESPACE TS_UTILISATEURS;

ALTER TABLE groups ADD CONSTRAINT fk_groups_parent
    FOREIGN KEY (groups_id) REFERENCES groups(id);

CREATE TABLE groups_users (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id        NUMBER NOT NULL,
    groups_id       NUMBER NOT NULL,
    is_manager      NUMBER(1) DEFAULT 0,
    is_userdelegate NUMBER(1) DEFAULT 0,
    CONSTRAINT fk_gu_user FOREIGN KEY (users_id) REFERENCES users(id),
    CONSTRAINT fk_gu_group FOREIGN KEY (groups_id) REFERENCES groups(id),
    CONSTRAINT uq_group_user UNIQUE (users_id, groups_id)
) TABLESPACE TS_UTILISATEURS;

-- =========================
-- TABLES MATERIELS
-- =========================

CREATE TABLE computers (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities_id     NUMBER NOT NULL,
    name            VARCHAR2(255),
    serial          VARCHAR2(255),
    otherserial     VARCHAR2(255),
    uuid            VARCHAR2(255),
    users_id        NUMBER,
    users_id_tech   NUMBER,
    locations_id    NUMBER,
    asset_types_id  NUMBER,
    asset_models_id NUMBER,
    manufacturers_id NUMBER,
    states_id       NUMBER,
    networks_id     NUMBER,
    notes           CLOB,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_comp_entity FOREIGN KEY (entities_id) REFERENCES entities(id),
    CONSTRAINT fk_comp_user FOREIGN KEY (users_id) REFERENCES users(id),
    CONSTRAINT fk_comp_tech FOREIGN KEY (users_id_tech) REFERENCES users(id),
    CONSTRAINT fk_comp_loc FOREIGN KEY (locations_id) REFERENCES locations(id),
    CONSTRAINT fk_comp_type FOREIGN KEY (asset_types_id) REFERENCES asset_types(id),
    CONSTRAINT fk_comp_model FOREIGN KEY (asset_models_id) REFERENCES asset_models(id),
    CONSTRAINT fk_comp_manuf FOREIGN KEY (manufacturers_id) REFERENCES manufacturers(id),
    CONSTRAINT fk_comp_state FOREIGN KEY (states_id) REFERENCES states(id),
    CONSTRAINT fk_comp_net FOREIGN KEY (networks_id) REFERENCES networks(id),
    CONSTRAINT uq_comp_entity_serial UNIQUE (entities_id, serial)
) TABLESPACE TS_MATERIEL;

CREATE TABLE monitors (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities_id     NUMBER NOT NULL,
    name            VARCHAR2(255),
    serial          VARCHAR2(255),
    size_monitor    NUMBER(5,2),
    users_id        NUMBER,
    locations_id    NUMBER,
    asset_types_id  NUMBER,
    asset_models_id NUMBER,
    manufacturers_id NUMBER,
    states_id       NUMBER,
    notes           CLOB,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_mon_entity FOREIGN KEY (entities_id) REFERENCES entities(id),
    CONSTRAINT fk_mon_user FOREIGN KEY (users_id) REFERENCES users(id),
    CONSTRAINT fk_mon_loc FOREIGN KEY (locations_id) REFERENCES locations(id),
    CONSTRAINT fk_mon_type FOREIGN KEY (asset_types_id) REFERENCES asset_types(id),
    CONSTRAINT fk_mon_model FOREIGN KEY (asset_models_id) REFERENCES asset_models(id),
    CONSTRAINT fk_mon_manuf FOREIGN KEY (manufacturers_id) REFERENCES manufacturers(id),
    CONSTRAINT fk_mon_state FOREIGN KEY (states_id) REFERENCES states(id)
) TABLESPACE TS_MATERIEL;

CREATE TABLE peripherals (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities_id     NUMBER NOT NULL,
    name            VARCHAR2(255),
    serial          VARCHAR2(255),
    users_id        NUMBER,
    locations_id    NUMBER,
    asset_types_id  NUMBER,
    manufacturers_id NUMBER,
    states_id       NUMBER,
    notes           CLOB,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_per_entity FOREIGN KEY (entities_id) REFERENCES entities(id),
    CONSTRAINT fk_per_user FOREIGN KEY (users_id) REFERENCES users(id),
    CONSTRAINT fk_per_loc FOREIGN KEY (locations_id) REFERENCES locations(id),
    CONSTRAINT fk_per_type FOREIGN KEY (asset_types_id) REFERENCES asset_types(id),
    CONSTRAINT fk_per_manuf FOREIGN KEY (manufacturers_id) REFERENCES manufacturers(id),
    CONSTRAINT fk_per_state FOREIGN KEY (states_id) REFERENCES states(id)
) TABLESPACE TS_MATERIEL;

CREATE TABLE printers (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities_id     NUMBER NOT NULL,
    name            VARCHAR2(255),
    serial          VARCHAR2(255),
    users_id        NUMBER,
    locations_id    NUMBER,
    asset_types_id  NUMBER,
    manufacturers_id NUMBER,
    states_id       NUMBER,
    networks_id     NUMBER,
    notes           CLOB,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_pri_entity FOREIGN KEY (entities_id) REFERENCES entities(id),
    CONSTRAINT fk_pri_user FOREIGN KEY (users_id) REFERENCES users(id),
    CONSTRAINT fk_pri_loc FOREIGN KEY (locations_id) REFERENCES locations(id),
    CONSTRAINT fk_pri_type FOREIGN KEY (asset_types_id) REFERENCES asset_types(id),
    CONSTRAINT fk_pri_manuf FOREIGN KEY (manufacturers_id) REFERENCES manufacturers(id),
    CONSTRAINT fk_pri_state FOREIGN KEY (states_id) REFERENCES states(id),
    CONSTRAINT fk_pri_net FOREIGN KEY (networks_id) REFERENCES networks(id)
) TABLESPACE TS_MATERIEL;

CREATE TABLE phones (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities_id     NUMBER NOT NULL,
    name            VARCHAR2(255),
    serial          VARCHAR2(255),
    users_id        NUMBER,
    locations_id    NUMBER,
    asset_types_id  NUMBER,
    manufacturers_id NUMBER,
    states_id       NUMBER,
    notes           CLOB,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_pho_entity FOREIGN KEY (entities_id) REFERENCES entities(id),
    CONSTRAINT fk_pho_user FOREIGN KEY (users_id) REFERENCES users(id),
    CONSTRAINT fk_pho_loc FOREIGN KEY (locations_id) REFERENCES locations(id),
    CONSTRAINT fk_pho_type FOREIGN KEY (asset_types_id) REFERENCES asset_types(id),
    CONSTRAINT fk_pho_manuf FOREIGN KEY (manufacturers_id) REFERENCES manufacturers(id),
    CONSTRAINT fk_pho_state FOREIGN KEY (states_id) REFERENCES states(id)
) TABLESPACE TS_MATERIEL;

CREATE TABLE network_equipments (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities_id     NUMBER NOT NULL,
    name            VARCHAR2(255),
    serial          VARCHAR2(255),
    ram             NUMBER,
    users_id        NUMBER,
    locations_id    NUMBER,
    asset_types_id  NUMBER,
    asset_models_id NUMBER,
    manufacturers_id NUMBER,
    states_id       NUMBER,
    networks_id     NUMBER,
    notes           CLOB,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_neq_entity FOREIGN KEY (entities_id) REFERENCES entities(id),
    CONSTRAINT fk_neq_user FOREIGN KEY (users_id) REFERENCES users(id),
    CONSTRAINT fk_neq_loc FOREIGN KEY (locations_id) REFERENCES locations(id),
    CONSTRAINT fk_neq_type FOREIGN KEY (asset_types_id) REFERENCES asset_types(id),
    CONSTRAINT fk_neq_model FOREIGN KEY (asset_models_id) REFERENCES asset_models(id),
    CONSTRAINT fk_neq_manuf FOREIGN KEY (manufacturers_id) REFERENCES manufacturers(id),
    CONSTRAINT fk_neq_state FOREIGN KEY (states_id) REFERENCES states(id),
    CONSTRAINT fk_neq_net FOREIGN KEY (networks_id) REFERENCES networks(id)
) TABLESPACE TS_MATERIEL;

-- =========================
-- TABLES SUPPORT / TICKETS
-- =========================

CREATE TABLE ticket_categories (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(255) NOT NULL UNIQUE,
    description     VARCHAR2(1000),
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP
) TABLESPACE TS_SUPPORT;

-- Supprimer les tickets liés à un PC supprimé
ALTER TABLE tickets DROP CONSTRAINT fk_ticket_comp;
ALTER TABLE tickets ADD CONSTRAINT fk_ticket_comp 
FOREIGN KEY (computers_id) REFERENCES computers(id) ON DELETE CASCADE;

CREATE TABLE tickets (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities_id     NUMBER NOT NULL,
    title           VARCHAR2(255) NOT NULL,
    description     CLOB NOT NULL,
    status          VARCHAR2(30) DEFAULT 'NOUVEAU' NOT NULL
        CHECK (status IN ('NOUVEAU','ASSIGNE','EN_COURS','EN_ATTENTE','RESOLU','CLOS','ANNULE')),
    priority        VARCHAR2(20) DEFAULT 'MOYENNE' NOT NULL
        CHECK (priority IN ('BASSE','MOYENNE','HAUTE','CRITIQUE')),
    urgency         VARCHAR2(20) DEFAULT 'MOYENNE' NOT NULL
        CHECK (urgency IN ('BASSE','MOYENNE','HAUTE','CRITIQUE')),
    impact          VARCHAR2(20) DEFAULT 'MOYEN' NOT NULL
        CHECK (impact IN ('FAIBLE','MOYEN','ELEVE','MAJEUR')),
    requester_users_id NUMBER NOT NULL,
    assigned_groups_id NUMBER,
    ticket_categories_id NUMBER,
    computers_id    NUMBER,
    monitors_id     NUMBER,
    peripherals_id  NUMBER,
    printers_id     NUMBER,
    phones_id       NUMBER,
    network_equipments_id NUMBER,
    resolution      CLOB,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_assigned   TIMESTAMP,
    date_resolved   TIMESTAMP,
    date_closed     TIMESTAMP,
    CONSTRAINT fk_ticket_entity FOREIGN KEY (entities_id) REFERENCES entities(id),
    CONSTRAINT fk_ticket_requester FOREIGN KEY (requester_users_id) REFERENCES users(id),
    CONSTRAINT fk_ticket_assigned_group FOREIGN KEY (assigned_groups_id) REFERENCES groups(id),
    CONSTRAINT fk_ticket_category FOREIGN KEY (ticket_categories_id) REFERENCES ticket_categories(id),
    CONSTRAINT fk_ticket_comp FOREIGN KEY (computers_id) REFERENCES computers(id),
    CONSTRAINT fk_ticket_mon FOREIGN KEY (monitors_id) REFERENCES monitors(id),
    CONSTRAINT fk_ticket_per FOREIGN KEY (peripherals_id) REFERENCES peripherals(id),
    CONSTRAINT fk_ticket_pri FOREIGN KEY (printers_id) REFERENCES printers(id),
    CONSTRAINT fk_ticket_pho FOREIGN KEY (phones_id) REFERENCES phones(id),
    CONSTRAINT fk_ticket_neq FOREIGN KEY (network_equipments_id) REFERENCES network_equipments(id),
    CONSTRAINT chk_ticket_one_asset CHECK (
        (CASE WHEN computers_id IS NOT NULL THEN 1 ELSE 0 END +
         CASE WHEN monitors_id IS NOT NULL THEN 1 ELSE 0 END +
         CASE WHEN peripherals_id IS NOT NULL THEN 1 ELSE 0 END +
         CASE WHEN printers_id IS NOT NULL THEN 1 ELSE 0 END +
         CASE WHEN phones_id IS NOT NULL THEN 1 ELSE 0 END +
         CASE WHEN network_equipments_id IS NOT NULL THEN 1 ELSE 0 END) = 1
    )
) TABLESPACE TS_SUPPORT;

CREATE TABLE ticket_users (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tickets_id      NUMBER NOT NULL,
    users_id        NUMBER NOT NULL,
    role            VARCHAR2(30) DEFAULT 'TECHNICIEN' NOT NULL
        CHECK (role IN ('TECHNICIEN')),
    assigned_by     NUMBER,
    date_assigned   TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_tu_ticket FOREIGN KEY (tickets_id) REFERENCES tickets(id),
    CONSTRAINT fk_tu_user FOREIGN KEY (users_id) REFERENCES users(id),
    CONSTRAINT fk_tu_assigned_by FOREIGN KEY (assigned_by) REFERENCES users(id),
    CONSTRAINT uq_ticket_user UNIQUE (tickets_id, users_id)
) TABLESPACE TS_SUPPORT;

CREATE TABLE ticket_followups (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tickets_id      NUMBER NOT NULL,
    users_id        NUMBER NOT NULL,
    content         CLOB NOT NULL,
    is_private      NUMBER(1) DEFAULT 0 CHECK (is_private IN (0, 1)),
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_tf_ticket FOREIGN KEY (tickets_id) REFERENCES tickets(id),
    CONSTRAINT fk_tf_user FOREIGN KEY (users_id) REFERENCES users(id)
) TABLESPACE TS_SUPPORT;

-- =========================
-- TABLES RESEAU
-- =========================

CREATE TABLE fqdns (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities_id     NUMBER NOT NULL,
    name            VARCHAR2(255) NOT NULL,
    fqdn            VARCHAR2(255) NOT NULL,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_fqdns_entity FOREIGN KEY (entities_id) REFERENCES entities(id)
) TABLESPACE TS_RESEAU;

-- Supprimer les ports si le PC disparaît
ALTER TABLE network_ports DROP CONSTRAINT fk_np_comp;
ALTER TABLE network_ports ADD CONSTRAINT fk_np_comp 
FOREIGN KEY (computers_id) REFERENCES computers(id) ON DELETE CASCADE;

CREATE TABLE network_ports (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities_id             NUMBER NOT NULL,
    name                    VARCHAR2(255),
    mac                     VARCHAR2(50),
    instantiation_type      VARCHAR2(100),
    logical_number          NUMBER DEFAULT 0,
    -- FK explicites remplaçant le polymorphisme GLPI
    computers_id            NUMBER,
    monitors_id             NUMBER,
    peripherals_id          NUMBER,
    printers_id             NUMBER,
    phones_id               NUMBER,
    network_equipments_id   NUMBER,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_np_entity FOREIGN KEY (entities_id) REFERENCES entities(id),
    CONSTRAINT fk_np_comp FOREIGN KEY (computers_id) REFERENCES computers(id),
    CONSTRAINT fk_np_mon FOREIGN KEY (monitors_id) REFERENCES monitors(id),
    CONSTRAINT fk_np_per FOREIGN KEY (peripherals_id) REFERENCES peripherals(id),
    CONSTRAINT fk_np_pri FOREIGN KEY (printers_id) REFERENCES printers(id),
    CONSTRAINT fk_np_pho FOREIGN KEY (phones_id) REFERENCES phones(id),
    CONSTRAINT fk_np_neq FOREIGN KEY (network_equipments_id) REFERENCES network_equipments(id),
    -- Exactement un parent doit être renseigné
    CONSTRAINT chk_port_one_parent CHECK (
        (CASE WHEN computers_id IS NOT NULL THEN 1 ELSE 0 END +
         CASE WHEN monitors_id IS NOT NULL THEN 1 ELSE 0 END +
         CASE WHEN peripherals_id IS NOT NULL THEN 1 ELSE 0 END +
         CASE WHEN printers_id IS NOT NULL THEN 1 ELSE 0 END +
         CASE WHEN phones_id IS NOT NULL THEN 1 ELSE 0 END +
         CASE WHEN network_equipments_id IS NOT NULL THEN 1 ELSE 0 END) = 1
    )
) TABLESPACE TS_RESEAU;

CREATE TABLE network_names (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_ports_id NUMBER NOT NULL,
    name            VARCHAR2(255),
    fqdns_id        NUMBER,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_nn_port FOREIGN KEY (network_ports_id) REFERENCES network_ports(id),
    CONSTRAINT fk_nn_fqdn FOREIGN KEY (fqdns_id) REFERENCES fqdns(id)
) TABLESPACE TS_RESEAU;

CREATE TABLE ip_addresses (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities_id     NUMBER NOT NULL,
    network_names_id NUMBER,
    name            VARCHAR2(255) NOT NULL,
    version         NUMBER(1) DEFAULT 4 CHECK (version IN (4, 6)),
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_ip_entity FOREIGN KEY (entities_id) REFERENCES entities(id),
    CONSTRAINT fk_ip_nn FOREIGN KEY (network_names_id) REFERENCES network_names(id)
) TABLESPACE TS_RESEAU;

CREATE TABLE network_connections (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_ports_id_1 NUMBER NOT NULL,
    network_ports_id_2 NUMBER NOT NULL,
    CONSTRAINT fk_nc_port1 FOREIGN KEY (network_ports_id_1) REFERENCES network_ports(id),
    CONSTRAINT fk_nc_port2 FOREIGN KEY (network_ports_id_2) REFERENCES network_ports(id),
    CONSTRAINT chk_nc_diff CHECK (network_ports_id_1 != network_ports_id_2)
) TABLESPACE TS_RESEAU;

CREATE TABLE vlans (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities_id     NUMBER NOT NULL,
    name            VARCHAR2(255) NOT NULL,
    tag             NUMBER NOT NULL,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_vlans_entity FOREIGN KEY (entities_id) REFERENCES entities(id),
    CONSTRAINT uq_vlan_tag UNIQUE (entities_id, tag)
) TABLESPACE TS_RESEAU;

CREATE TABLE network_port_vlans (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_ports_id NUMBER NOT NULL,
    vlans_id        NUMBER NOT NULL,
    tagged          NUMBER(1) DEFAULT 0,
    CONSTRAINT fk_npv_port FOREIGN KEY (network_ports_id) REFERENCES network_ports(id),
    CONSTRAINT fk_npv_vlan FOREIGN KEY (vlans_id) REFERENCES vlans(id),
    CONSTRAINT uq_port_vlan UNIQUE (network_ports_id, vlans_id)
) TABLESPACE TS_RESEAU;

CREATE TABLE ip_networks (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities_id     NUMBER NOT NULL,
    name            VARCHAR2(255),
    address         VARCHAR2(40) NOT NULL,
    netmask         VARCHAR2(40) NOT NULL,
    gateway         VARCHAR2(40),
    ip_networks_id  NUMBER,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_ipn_entity FOREIGN KEY (entities_id) REFERENCES entities(id)
) TABLESPACE TS_RESEAU;

ALTER TABLE ip_networks ADD CONSTRAINT fk_ipn_parent
    FOREIGN KEY (ip_networks_id) REFERENCES ip_networks(id);

CREATE TABLE ip_network_vlans (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_networks_id  NUMBER NOT NULL,
    vlans_id        NUMBER NOT NULL,
    CONSTRAINT fk_inv_ipn FOREIGN KEY (ip_networks_id) REFERENCES ip_networks(id),
    CONSTRAINT fk_inv_vlan FOREIGN KEY (vlans_id) REFERENCES vlans(id),
    CONSTRAINT uq_ipn_vlan UNIQUE (ip_networks_id, vlans_id)
) TABLESPACE TS_RESEAU;

CREATE TABLE sockets (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities_id     NUMBER NOT NULL,
    locations_id    NUMBER,
    name            VARCHAR2(255),
    network_ports_id NUMBER,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_sock_entity FOREIGN KEY (entities_id) REFERENCES entities(id),
    CONSTRAINT fk_sock_loc FOREIGN KEY (locations_id) REFERENCES locations(id),
    CONSTRAINT fk_sock_port FOREIGN KEY (network_ports_id) REFERENCES network_ports(id)
) TABLESPACE TS_RESEAU;

CREATE TABLE cables (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities_id     NUMBER NOT NULL,
    name            VARCHAR2(255),
    sockets_id_a    NUMBER,
    sockets_id_b    NUMBER,
    date_creation   TIMESTAMP DEFAULT SYSTIMESTAMP,
    date_mod        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_cab_entity FOREIGN KEY (entities_id) REFERENCES entities(id),
    CONSTRAINT fk_cab_sock_a FOREIGN KEY (sockets_id_a) REFERENCES sockets(id),
    CONSTRAINT fk_cab_sock_b FOREIGN KEY (sockets_id_b) REFERENCES sockets(id)
) TABLESPACE TS_RESEAU;

-- =========================
-- TABLE D'AUDIT
-- =========================

CREATE TABLE audit_log (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name      VARCHAR2(100) NOT NULL,
    record_id       NUMBER NOT NULL,
    action          VARCHAR2(10) NOT NULL CHECK (action IN ('INSERT','UPDATE','DELETE')),
    old_values      CLOB,
    new_values      CLOB,
    changed_by      VARCHAR2(100) DEFAULT USER,
    change_date     TIMESTAMP DEFAULT SYSTIMESTAMP
) TABLESPACE TS_MATERIEL;

-- =========================
-- TABLE D'ARCHIVAGE
-- =========================

CREATE TABLE archives_materiel (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_table    VARCHAR2(100) NOT NULL,
    source_id       NUMBER NOT NULL,
    data            CLOB NOT NULL,
    archived_by     VARCHAR2(100) DEFAULT USER,
    archive_date    TIMESTAMP DEFAULT SYSTIMESTAMP
) TABLESPACE TS_MATERIEL;
