-- ============================================================
-- 03_users_roles.sql
-- Utilisateurs Oracle, Rôles et Privilèges
-- Oracle XE — Gestion fine des accès multi-sites
-- ============================================================

-- =========================
-- CRÉATION DES RÔLES
-- =========================

-- Administrateur : accès total
CREATE ROLE ROLE_ADMIN;

-- Technicien : gestion des matériels et réseaux
CREATE ROLE ROLE_TECHNICIEN;

-- Consultant : lecture seule
CREATE ROLE ROLE_CONSULTANT;

-- Manager de site : gestion complète sur son site
CREATE ROLE ROLE_MANAGER_SITE;

-- =========================
-- PRIVILÈGES DU RÔLE ADMIN
-- =========================

-- Accès complet sur toutes les tables
GRANT SELECT, INSERT, UPDATE, DELETE ON entities TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON locations TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON manufacturers TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON states TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON networks TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON asset_types TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON asset_models TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON users TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON profiles TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON profile_rights TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON profiles_users TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON groups TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON groups_users TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON computers TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON monitors TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON peripherals TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON printers TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON phones TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON network_equipments TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON network_ports TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON network_connections TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON vlans TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON network_port_vlans TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ip_networks TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ip_addresses TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON cables TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON sockets TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON audit_log TO ROLE_ADMIN;

-- =========================
-- PRIVILÈGES DU RÔLE TECHNICIEN
-- =========================

-- Lecture sur les référentiels
GRANT SELECT ON entities TO ROLE_TECHNICIEN;
GRANT SELECT ON locations TO ROLE_TECHNICIEN;
GRANT SELECT ON manufacturers TO ROLE_TECHNICIEN;
GRANT SELECT ON states TO ROLE_TECHNICIEN;
GRANT SELECT ON networks TO ROLE_TECHNICIEN;
GRANT SELECT ON asset_types TO ROLE_TECHNICIEN;
GRANT SELECT ON asset_models TO ROLE_TECHNICIEN;
GRANT SELECT ON users TO ROLE_TECHNICIEN;
GRANT SELECT ON profiles TO ROLE_TECHNICIEN;

-- Gestion des matériels (CRUD)
GRANT SELECT, INSERT, UPDATE, DELETE ON computers TO ROLE_TECHNICIEN;
GRANT SELECT, INSERT, UPDATE, DELETE ON monitors TO ROLE_TECHNICIEN;
GRANT SELECT, INSERT, UPDATE, DELETE ON peripherals TO ROLE_TECHNICIEN;
GRANT SELECT, INSERT, UPDATE, DELETE ON printers TO ROLE_TECHNICIEN;
GRANT SELECT, INSERT, UPDATE, DELETE ON phones TO ROLE_TECHNICIEN;
GRANT SELECT, INSERT, UPDATE, DELETE ON network_equipments TO ROLE_TECHNICIEN;

-- Gestion du réseau
GRANT SELECT, INSERT, UPDATE, DELETE ON network_ports TO ROLE_TECHNICIEN;
GRANT SELECT, INSERT, UPDATE, DELETE ON network_connections TO ROLE_TECHNICIEN;
GRANT SELECT, INSERT, UPDATE ON vlans TO ROLE_TECHNICIEN;
GRANT SELECT, INSERT, UPDATE ON network_port_vlans TO ROLE_TECHNICIEN;
GRANT SELECT ON ip_networks TO ROLE_TECHNICIEN;
GRANT SELECT, INSERT, UPDATE ON ip_addresses TO ROLE_TECHNICIEN;
GRANT SELECT, INSERT, UPDATE ON cables TO ROLE_TECHNICIEN;
GRANT SELECT, INSERT, UPDATE ON sockets TO ROLE_TECHNICIEN;

-- Lecture audit
GRANT SELECT ON audit_log TO ROLE_TECHNICIEN;

-- =========================
-- PRIVILÈGES DU RÔLE CONSULTANT
-- =========================

-- Lecture seule sur tout
GRANT SELECT ON entities TO ROLE_CONSULTANT;
GRANT SELECT ON locations TO ROLE_CONSULTANT;
GRANT SELECT ON manufacturers TO ROLE_CONSULTANT;
GRANT SELECT ON states TO ROLE_CONSULTANT;
GRANT SELECT ON networks TO ROLE_CONSULTANT;
GRANT SELECT ON asset_types TO ROLE_CONSULTANT;
GRANT SELECT ON asset_models TO ROLE_CONSULTANT;
GRANT SELECT ON users TO ROLE_CONSULTANT;
GRANT SELECT ON profiles TO ROLE_CONSULTANT;
GRANT SELECT ON computers TO ROLE_CONSULTANT;
GRANT SELECT ON monitors TO ROLE_CONSULTANT;
GRANT SELECT ON peripherals TO ROLE_CONSULTANT;
GRANT SELECT ON printers TO ROLE_CONSULTANT;
GRANT SELECT ON phones TO ROLE_CONSULTANT;
GRANT SELECT ON network_equipments TO ROLE_CONSULTANT;
GRANT SELECT ON network_ports TO ROLE_CONSULTANT;
GRANT SELECT ON vlans TO ROLE_CONSULTANT;
GRANT SELECT ON ip_networks TO ROLE_CONSULTANT;
GRANT SELECT ON ip_addresses TO ROLE_CONSULTANT;

-- =========================
-- PRIVILÈGES DU RÔLE MANAGER_SITE
-- =========================

-- Mêmes droits que technicien + gestion utilisateurs/profils
GRANT ROLE_TECHNICIEN TO ROLE_MANAGER_SITE;
GRANT SELECT, INSERT, UPDATE ON users TO ROLE_MANAGER_SITE;
GRANT SELECT, INSERT, UPDATE, DELETE ON profiles_users TO ROLE_MANAGER_SITE;
GRANT SELECT, INSERT, UPDATE, DELETE ON groups TO ROLE_MANAGER_SITE;
GRANT SELECT, INSERT, UPDATE, DELETE ON groups_users TO ROLE_MANAGER_SITE;
GRANT SELECT ON audit_log TO ROLE_MANAGER_SITE;

-- =========================
-- CRÉATION DES UTILISATEURS ORACLE
-- =========================

-- Administrateur global
CREATE USER admin_glpi IDENTIFIED BY AdminGlpi2026
    DEFAULT TABLESPACE TS_MATERIEL
    TEMPORARY TABLESPACE TS_TEMP_GLPI
    QUOTA UNLIMITED ON TS_MATERIEL
    QUOTA UNLIMITED ON TS_UTILISATEURS
    QUOTA UNLIMITED ON TS_RESEAU
    QUOTA UNLIMITED ON TS_INDEX;

GRANT CONNECT, RESOURCE TO admin_glpi;
GRANT ROLE_ADMIN TO admin_glpi;

-- Technicien site Cergy
CREATE USER tech_cergy IDENTIFIED BY TechCergy2026
    DEFAULT TABLESPACE TS_MATERIEL
    TEMPORARY TABLESPACE TS_TEMP_GLPI
    QUOTA 100M ON TS_MATERIEL
    QUOTA 50M ON TS_RESEAU;

GRANT CONNECT TO tech_cergy;
GRANT ROLE_TECHNICIEN TO tech_cergy;

-- Technicien site Pau
CREATE USER tech_pau IDENTIFIED BY TechPau2026
    DEFAULT TABLESPACE TS_MATERIEL
    TEMPORARY TABLESPACE TS_TEMP_GLPI
    QUOTA 100M ON TS_MATERIEL
    QUOTA 50M ON TS_RESEAU;

GRANT CONNECT TO tech_pau;
GRANT ROLE_TECHNICIEN TO tech_pau;

-- Consultant (lecture seule)
CREATE USER consultant IDENTIFIED BY Consultant2026
    DEFAULT TABLESPACE TS_MATERIEL
    TEMPORARY TABLESPACE TS_TEMP_GLPI;

GRANT CONNECT TO consultant;
GRANT ROLE_CONSULTANT TO consultant;

-- Manager Cergy
CREATE USER manager_cergy IDENTIFIED BY ManagerCergy2026
    DEFAULT TABLESPACE TS_MATERIEL
    TEMPORARY TABLESPACE TS_TEMP_GLPI
    QUOTA 200M ON TS_MATERIEL
    QUOTA 100M ON TS_UTILISATEURS
    QUOTA 100M ON TS_RESEAU;

GRANT CONNECT TO manager_cergy;
GRANT ROLE_MANAGER_SITE TO manager_cergy;

-- Manager Pau
CREATE USER manager_pau IDENTIFIED BY ManagerPau2026
    DEFAULT TABLESPACE TS_MATERIEL
    TEMPORARY TABLESPACE TS_TEMP_GLPI
    QUOTA 200M ON TS_MATERIEL
    QUOTA 100M ON TS_UTILISATEURS
    QUOTA 100M ON TS_RESEAU;

GRANT CONNECT TO manager_pau;
GRANT ROLE_MANAGER_SITE TO manager_pau;

-- Accès aux vues pour tous les utilisateurs
-- (à exécuter après création des vues dans 05_views.sql)
-- GRANT SELECT ON V_INVENTAIRE_COMPLET TO ROLE_CONSULTANT, ROLE_TECHNICIEN, ROLE_MANAGER_SITE, ROLE_ADMIN;
-- GRANT SELECT ON V_MATERIEL_PAR_SITE TO ROLE_CONSULTANT, ROLE_TECHNICIEN, ROLE_MANAGER_SITE, ROLE_ADMIN;
-- GRANT SELECT ON V_UTILISATEURS_PROFILS TO ROLE_MANAGER_SITE, ROLE_ADMIN;
-- GRANT SELECT ON V_TOPOLOGIE_RESEAU TO ROLE_TECHNICIEN, ROLE_MANAGER_SITE, ROLE_ADMIN;
-- GRANT SELECT ON V_STATISTIQUES_SITE TO ROLE_MANAGER_SITE, ROLE_ADMIN;
