-- ============================================================
-- 03_users_roles.sql
-- Utilisateurs Oracle, roles et privileges - Schema simplifie
-- Oracle XE
-- ============================================================

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE ROLE ROLE_ADMIN;
CREATE ROLE ROLE_TECHNICIEN;
CREATE ROLE ROLE_CONSULTANT;
CREATE ROLE ROLE_MANAGER_SITE;

-- =========================
-- ROLE_ADMIN
-- =========================

GRANT SELECT, INSERT, UPDATE, DELETE ON entities TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON locations TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON manufacturers TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON states TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON networks TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON asset_models TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON users TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON profiles TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON profiles_users TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON groups TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON groups_users TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON assets TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ticket_categories TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON tickets TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ticket_users TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ticket_followups TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON network_ports TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON network_connections TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON vlans TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON network_port_vlans TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ip_networks TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ip_addresses TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON audit_log TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON archives_materiel TO ROLE_ADMIN;

-- =========================
-- ROLE_TECHNICIEN
-- =========================

GRANT SELECT ON entities TO ROLE_TECHNICIEN;
GRANT SELECT ON locations TO ROLE_TECHNICIEN;
GRANT SELECT ON manufacturers TO ROLE_TECHNICIEN;
GRANT SELECT ON states TO ROLE_TECHNICIEN;
GRANT SELECT ON networks TO ROLE_TECHNICIEN;
GRANT SELECT ON asset_models TO ROLE_TECHNICIEN;
GRANT SELECT ON users TO ROLE_TECHNICIEN;
GRANT SELECT ON profiles TO ROLE_TECHNICIEN;
GRANT SELECT ON groups TO ROLE_TECHNICIEN;
GRANT SELECT, INSERT, UPDATE, DELETE ON assets TO ROLE_TECHNICIEN;
GRANT SELECT ON ticket_categories TO ROLE_TECHNICIEN;
GRANT SELECT, INSERT, UPDATE ON tickets TO ROLE_TECHNICIEN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ticket_users TO ROLE_TECHNICIEN;
GRANT SELECT, INSERT, UPDATE ON ticket_followups TO ROLE_TECHNICIEN;
GRANT SELECT, INSERT, UPDATE, DELETE ON network_ports TO ROLE_TECHNICIEN;
GRANT SELECT, INSERT, UPDATE, DELETE ON network_connections TO ROLE_TECHNICIEN;
GRANT SELECT, INSERT, UPDATE ON vlans TO ROLE_TECHNICIEN;
GRANT SELECT, INSERT, UPDATE ON network_port_vlans TO ROLE_TECHNICIEN;
GRANT SELECT, INSERT, UPDATE ON ip_addresses TO ROLE_TECHNICIEN;
GRANT SELECT ON ip_networks TO ROLE_TECHNICIEN;
GRANT SELECT ON audit_log TO ROLE_TECHNICIEN;

-- =========================
-- ROLE_CONSULTANT
-- =========================

GRANT SELECT ON entities TO ROLE_CONSULTANT;
GRANT SELECT ON locations TO ROLE_CONSULTANT;
GRANT SELECT ON manufacturers TO ROLE_CONSULTANT;
GRANT SELECT ON states TO ROLE_CONSULTANT;
GRANT SELECT ON networks TO ROLE_CONSULTANT;
GRANT SELECT ON asset_models TO ROLE_CONSULTANT;
GRANT SELECT ON users TO ROLE_CONSULTANT;
GRANT SELECT ON profiles TO ROLE_CONSULTANT;
GRANT SELECT ON groups TO ROLE_CONSULTANT;
GRANT SELECT ON assets TO ROLE_CONSULTANT;
GRANT SELECT ON ticket_categories TO ROLE_CONSULTANT;
GRANT SELECT ON tickets TO ROLE_CONSULTANT;
GRANT SELECT ON ticket_users TO ROLE_CONSULTANT;
GRANT SELECT ON ticket_followups TO ROLE_CONSULTANT;
GRANT SELECT ON network_ports TO ROLE_CONSULTANT;
GRANT SELECT ON vlans TO ROLE_CONSULTANT;
GRANT SELECT ON ip_networks TO ROLE_CONSULTANT;
GRANT SELECT ON ip_addresses TO ROLE_CONSULTANT;

-- =========================
-- ROLE_MANAGER_SITE
-- =========================

GRANT ROLE_TECHNICIEN TO ROLE_MANAGER_SITE;
GRANT SELECT, INSERT, UPDATE ON users TO ROLE_MANAGER_SITE;
GRANT SELECT, INSERT, UPDATE, DELETE ON profiles_users TO ROLE_MANAGER_SITE;
GRANT SELECT, INSERT, UPDATE, DELETE ON groups TO ROLE_MANAGER_SITE;
GRANT SELECT, INSERT, UPDATE, DELETE ON groups_users TO ROLE_MANAGER_SITE;

-- Avant execution SQL*Plus/SQLcl, definir les mots de passe :
-- DEFINE ADMIN_GLPI_PASSWORD = mot_de_passe_admin
-- DEFINE TECH_CERGY_PASSWORD = mot_de_passe_tech_cergy
-- DEFINE TECH_PAU_PASSWORD = mot_de_passe_tech_pau
-- DEFINE CONSULTANT_PASSWORD = mot_de_passe_consultant
-- DEFINE MANAGER_CERGY_PASSWORD = mot_de_passe_manager_cergy
-- DEFINE MANAGER_PAU_PASSWORD = mot_de_passe_manager_pau

CREATE USER admin_glpi IDENTIFIED BY "&&ADMIN_GLPI_PASSWORD"
    DEFAULT TABLESPACE TS_MATERIEL
    TEMPORARY TABLESPACE TS_TEMP_GLPI
    QUOTA UNLIMITED ON TS_MATERIEL
    QUOTA UNLIMITED ON TS_UTILISATEURS
    QUOTA UNLIMITED ON TS_RESEAU
    QUOTA UNLIMITED ON TS_SUPPORT
    QUOTA UNLIMITED ON TS_INDEX;

GRANT CONNECT, RESOURCE TO admin_glpi;
GRANT ROLE_ADMIN TO admin_glpi;

CREATE USER tech_cergy IDENTIFIED BY "&&TECH_CERGY_PASSWORD"
    DEFAULT TABLESPACE TS_MATERIEL
    TEMPORARY TABLESPACE TS_TEMP_GLPI
    QUOTA 100M ON TS_MATERIEL
    QUOTA 50M ON TS_RESEAU
    QUOTA 50M ON TS_SUPPORT;

GRANT CONNECT TO tech_cergy;
GRANT ROLE_TECHNICIEN TO tech_cergy;

CREATE USER tech_pau IDENTIFIED BY "&&TECH_PAU_PASSWORD"
    DEFAULT TABLESPACE TS_MATERIEL
    TEMPORARY TABLESPACE TS_TEMP_GLPI
    QUOTA 100M ON TS_MATERIEL
    QUOTA 50M ON TS_RESEAU
    QUOTA 50M ON TS_SUPPORT;

GRANT CONNECT TO tech_pau;
GRANT ROLE_TECHNICIEN TO tech_pau;

CREATE USER consultant IDENTIFIED BY "&&CONSULTANT_PASSWORD"
    DEFAULT TABLESPACE TS_MATERIEL
    TEMPORARY TABLESPACE TS_TEMP_GLPI;

GRANT CONNECT TO consultant;
GRANT ROLE_CONSULTANT TO consultant;

CREATE USER manager_cergy IDENTIFIED BY "&&MANAGER_CERGY_PASSWORD"
    DEFAULT TABLESPACE TS_MATERIEL
    TEMPORARY TABLESPACE TS_TEMP_GLPI
    QUOTA 200M ON TS_MATERIEL
    QUOTA 100M ON TS_UTILISATEURS
    QUOTA 100M ON TS_RESEAU
    QUOTA 50M ON TS_SUPPORT;

GRANT CONNECT TO manager_cergy;
GRANT ROLE_MANAGER_SITE TO manager_cergy;

CREATE USER manager_pau IDENTIFIED BY "&&MANAGER_PAU_PASSWORD"
    DEFAULT TABLESPACE TS_MATERIEL
    TEMPORARY TABLESPACE TS_TEMP_GLPI
    QUOTA 200M ON TS_MATERIEL
    QUOTA 100M ON TS_UTILISATEURS
    QUOTA 100M ON TS_RESEAU
    QUOTA 50M ON TS_SUPPORT;

GRANT CONNECT TO manager_pau;
GRANT ROLE_MANAGER_SITE TO manager_pau;

-- Grants de vues a executer apres 05_views.sql :
-- GRANT SELECT ON V_INVENTAIRE_COMPLET TO ROLE_CONSULTANT, ROLE_TECHNICIEN, ROLE_MANAGER_SITE, ROLE_ADMIN;
-- GRANT SELECT ON V_MATERIEL_PAR_SITE TO ROLE_CONSULTANT, ROLE_TECHNICIEN, ROLE_MANAGER_SITE, ROLE_ADMIN;
-- GRANT SELECT ON V_UTILISATEURS_PROFILS TO ROLE_MANAGER_SITE, ROLE_ADMIN;
-- GRANT SELECT ON V_TOPOLOGIE_RESEAU TO ROLE_TECHNICIEN, ROLE_MANAGER_SITE, ROLE_ADMIN;
-- GRANT SELECT ON V_STATISTIQUES_SITE TO ROLE_MANAGER_SITE, ROLE_ADMIN;
-- GRANT SELECT ON V_TICKETS_SUPPORT TO ROLE_CONSULTANT, ROLE_TECHNICIEN, ROLE_MANAGER_SITE, ROLE_ADMIN;
