-- ============================================================
-- 09_test_data.sql
-- Generation d'un jeu de test volumineux en PL/SQL
-- Oracle XE — Phase 3 : Tests de performance
-- ============================================================

SET SQLBLANKLINES ON
SET DEFINE OFF

-- Table pour stocker les temps de benchmark
CREATE TABLE benchmark_results (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_id      VARCHAR2(10),
    query_desc    VARCHAR2(200),
    scenario      VARCHAR2(20),
    execution_ms  NUMBER,
    rows_returned NUMBER,
    run_date      TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- =========================
-- PROCEDURE PRINCIPALE
-- =========================
CREATE OR REPLACE PROCEDURE SP_GENERER_JEU_DE_TEST
AS
    v_entity_cergy  NUMBER;
    v_entity_pau    NUMBER;
    v_loc_id        NUMBER;
    v_user_id       NUMBER;
    v_comp_id       NUMBER;
    v_port_id       NUMBER;
    v_type_id       NUMBER;
    v_model_id      NUMBER;
    v_manuf_id      NUMBER;
    v_state_id      NUMBER;
    v_net_id        NUMBER;
    v_vlan_id       NUMBER;
    v_neq_id        NUMBER;

    TYPE t_names IS TABLE OF VARCHAR2(100);
    v_prenoms t_names := t_names(
        'Jean','Marie','Pierre','Sophie','Thomas','Julie','Nicolas','Emma',
        'Alexandre','Camille','Lucas','Lea','Hugo','Chloe','Louis','Manon',
        'Gabriel','Alice','Raphael','Sarah','Arthur','Clara','Adam','Ines',
        'Paul','Charlotte','Victor','Juliette','Leo','Amelia');
    v_noms t_names := t_names(
        'Martin','Bernard','Dubois','Thomas','Robert','Richard','Petit',
        'Durand','Leroy','Moreau','Simon','Laurent','Lefebvre','Michel',
        'Garcia','David','Bertrand','Roux','Vincent','Fournier',
        'Morel','Girard','Andre','Mercier','Dupont');
    v_batiments t_names := t_names(
        'Batiment A','Batiment B','Batiment C','Batiment D','Batiment E');
    v_salles t_names := t_names(
        'Salle 101','Salle 102','Salle 201','Salle 202','Salle 301',
        'Salle Serveur','Bureau 1','Bureau 2','Amphi 1','Labo Info');
    v_fabricants t_names := t_names(
        'Dell','HP','Lenovo','Apple','Asus','Acer','Microsoft',
        'Cisco','Juniper','Aruba','Samsung','LG','Epson','Brother','Canon');
    v_etats t_names := t_names(
        'En service','En panne','En maintenance','Stocke','Reforme');
    v_reseaux t_names := t_names(
        'Ethernet','Wi-Fi','Fibre','VPN','4G-LTE');
    v_vlan_names t_names := t_names(
        'VLAN-Management','VLAN-Data','VLAN-VoIP','VLAN-Serveurs',
        'VLAN-DMZ','VLAN-Guests','VLAN-IoT','VLAN-Backup',
        'VLAN-Dev','VLAN-Prod');

    v_site_codes t_names := t_names('CERGY','PAU');
    v_depts t_names := t_names(
        'DSI','Ressources Humaines','Direction','Recherche','Enseignement',
        'Administration','Comptabilite','Logistique','Communication','Securite');

    v_counter NUMBER := 0;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== DEBUT GENERATION JEU DE TEST ===');
    DBMS_OUTPUT.PUT_LINE('Date: ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS'));

    -- =====================
    -- 1. FABRICANTS
    -- =====================
    FOR i IN 1..v_fabricants.COUNT LOOP
        DECLARE
            v_fabricant VARCHAR2(100) := v_fabricants(i);
        BEGIN
            INSERT INTO manufacturers (name) VALUES (v_fabricant);
        EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
        END;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('Fabricants: ' || v_fabricants.COUNT);

    -- =====================
    -- 2. ETATS
    -- =====================
    FOR i IN 1..v_etats.COUNT LOOP
        DECLARE
            v_etat VARCHAR2(100) := v_etats(i);
        BEGIN
            INSERT INTO states (name, entities_id,
                is_visible_computer, is_visible_monitor,
                is_visible_printer, is_visible_phone,
                is_visible_peripheral, is_visible_networkequip)
            VALUES (v_etat, NULL, 1, 1, 1, 1, 1, 1);
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('Etats: ' || v_etats.COUNT);

    -- =====================
    -- 3. RESEAUX
    -- =====================
    FOR i IN 1..v_reseaux.COUNT LOOP
        DECLARE
            v_reseau VARCHAR2(100) := v_reseaux(i);
        BEGIN
            INSERT INTO networks (name) VALUES (v_reseau);
        EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
        END;
    END LOOP;

    -- =====================
    -- 4. TYPES ET MODELES D'ASSETS
    -- =====================
    DECLARE
        TYPE t_cats IS TABLE OF VARCHAR2(50);
        v_cats t_cats := t_cats('COMPUTER','MONITOR','PERIPHERAL','PRINTER','PHONE','NETWORK_EQUIPMENT');
        v_type_names t_names;
        v_model_names t_names;
    BEGIN
        FOR c IN 1..v_cats.COUNT LOOP
            DECLARE
                v_category VARCHAR2(50) := v_cats(c);
            BEGIN
            CASE v_category
                WHEN 'COMPUTER' THEN
                    v_type_names := t_names('Desktop','Laptop','Serveur','Workstation');
                    v_model_names := t_names('OptiPlex 7090','ThinkPad T14','EliteBook 840','MacBook Pro','ProBook 450');
                WHEN 'MONITOR' THEN
                    v_type_names := t_names('Ecran LCD','Ecran LED','Ecran 4K');
                    v_model_names := t_names('U2722D','ThinkVision T24','E2422H','UltraSharp 27');
                WHEN 'PERIPHERAL' THEN
                    v_type_names := t_names('Clavier','Souris','Dock Station','Webcam');
                    v_model_names := t_names('MK270','M720','USB-C Dock','C920');
                WHEN 'PRINTER' THEN
                    v_type_names := t_names('Laser N&B','Laser Couleur','Jet Encre');
                    v_model_names := t_names('LaserJet Pro','Color LaserJet','WorkForce');
                WHEN 'PHONE' THEN
                    v_type_names := t_names('IP Phone','Softphone','DECT');
                    v_model_names := t_names('Cisco 8845','Yealink T46','Polycom VVX');
                WHEN 'NETWORK_EQUIPMENT' THEN
                    v_type_names := t_names('Switch','Routeur','Point Acces','Firewall');
                    v_model_names := t_names('Catalyst 9300','ISR 4321','Aruba AP','FortiGate 60');
            END CASE;
            FOR i IN 1..v_type_names.COUNT LOOP
                DECLARE
                    v_type_name VARCHAR2(100) := v_type_names(i);
                BEGIN
                    INSERT INTO asset_types (category, name) VALUES (v_category, v_type_name);
                EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
                END;
            END LOOP;
            FOR i IN 1..v_model_names.COUNT LOOP
                DECLARE
                    v_model_name VARCHAR2(100) := v_model_names(i);
                BEGIN
                    INSERT INTO asset_models (category, name) VALUES (v_category, v_model_name);
                EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
                END;
            END LOOP;
            END;
        END LOOP;
    END;
    DBMS_OUTPUT.PUT_LINE('Types et modeles crees.');

    -- =====================
    -- 5. PROFILS
    -- =====================
    BEGIN
        INSERT INTO profiles (name, interface, is_default) VALUES ('Super-Admin','central',0);
        INSERT INTO profiles (name, interface, is_default) VALUES ('Admin','central',0);
        INSERT INTO profiles (name, interface, is_default) VALUES ('Technicien','central',0);
        INSERT INTO profiles (name, interface, is_default) VALUES ('Observateur','central',1);
        INSERT INTO profiles (name, interface, is_default) VALUES ('Self-Service','helpdesk',0);
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
    END;

    -- Categories de tickets support
    BEGIN
        INSERT INTO ticket_categories (name, description)
        VALUES ('Incident materiel', 'Panne ou dysfonctionnement sur un equipement');
        INSERT INTO ticket_categories (name, description)
        VALUES ('Demande assistance', 'Besoin d''aide ou de diagnostic');
        INSERT INTO ticket_categories (name, description)
        VALUES ('Maintenance preventive', 'Intervention planifiee sur le parc');
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
    END;

    -- =====================
    -- 6. TITRES ET CATEGORIES UTILISATEURS
    -- =====================
    BEGIN
        INSERT INTO user_titles (name) VALUES ('M.');
        INSERT INTO user_titles (name) VALUES ('Mme');
        INSERT INTO user_titles (name) VALUES ('Dr');
        INSERT INTO user_titles (name) VALUES ('Pr');
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
    END;
    BEGIN
        INSERT INTO user_categories (name) VALUES ('Enseignant');
        INSERT INTO user_categories (name) VALUES ('Etudiant');
        INSERT INTO user_categories (name) VALUES ('Administratif');
        INSERT INTO user_categories (name) VALUES ('Technicien');
        INSERT INTO user_categories (name) VALUES ('Direction');
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
    END;

    COMMIT;

    -- =====================
    -- 7. ENTITES, LOCATIONS, USERS, MATERIELS par site
    -- =====================
    FOR s IN 1..v_site_codes.COUNT LOOP
        DECLARE
            v_site VARCHAR2(10) := v_site_codes(s);
            v_root_entity NUMBER;
            v_dept_entity NUMBER;
            v_loc_base NUMBER;
            v_title_max NUMBER;
            v_cat_max NUMBER;
            v_prof_max NUMBER;
            v_state_max NUMBER;
            v_manuf_max NUMBER;
            v_net_max NUMBER;
        BEGIN
            -- Entite racine du site
            INSERT INTO entities (name, hier_level, site_code, completename)
            VALUES ('CY Tech ' || v_site, 1, v_site, 'CY Tech ' || v_site)
            RETURNING id INTO v_root_entity;

            INSERT INTO groups (entities_id, name, completename)
            VALUES (v_root_entity, 'Service IT ' || v_site, 'CY Tech ' || v_site || ' > Service IT');

            -- Departements
            FOR d IN 1..v_depts.COUNT LOOP
                DECLARE
                    v_dept_name VARCHAR2(100) := v_depts(d);
                BEGIN
                INSERT INTO entities (name, entities_id, hier_level, site_code, completename)
                VALUES (v_dept_name || ' ' || v_site, v_root_entity, 2, v_site,
                        'CY Tech ' || v_site || ' > ' || v_dept_name)
                RETURNING id INTO v_dept_entity;

                -- Locations pour chaque departement
                FOR b IN 1..v_batiments.COUNT LOOP
                    IF MOD(b + d, 3) = 0 THEN
                        DECLARE
                            v_batiment VARCHAR2(100) := v_batiments(b);
                            v_salle VARCHAR2(100) := v_salles(MOD(d-1, v_salles.COUNT)+1);
                        BEGIN
                        INSERT INTO locations (entities_id, name, completename, building, room)
                        VALUES (v_dept_entity,
                                v_batiment || ' - ' || v_salle,
                                v_site || ' > ' || v_batiment,
                                v_batiment,
                                v_salle);
                        END;
                    END IF;
                END LOOP;
                END;
            END LOOP;

            COMMIT;

            -- Recuperer les max IDs pour les FK
            SELECT MAX(id) INTO v_title_max FROM user_titles;
            SELECT MAX(id) INTO v_cat_max FROM user_categories;
            SELECT MAX(id) INTO v_prof_max FROM profiles;
            SELECT MAX(id) INTO v_state_max FROM states;
            SELECT MAX(id) INTO v_manuf_max FROM manufacturers;
            SELECT MAX(id) INTO v_net_max FROM networks;

            -- =====================
            -- UTILISATEURS (500 par site)
            -- =====================
            FOR i IN 1..500 LOOP
                DECLARE
                    v_prenom VARCHAR2(100) := v_prenoms(MOD(i-1, v_prenoms.COUNT)+1);
                    v_nom VARCHAR2(100) := v_noms(MOD(i-1, v_noms.COUNT)+1);
                    v_login VARCHAR2(255) := LOWER(SUBSTR(v_prenom,1,1)) || LOWER(v_nom)
                                             || '_' || v_site || '_' || i;
                    v_ent_id NUMBER;
                BEGIN
                    SELECT id INTO v_ent_id FROM (
                        SELECT id FROM entities WHERE site_code = v_site
                        ORDER BY DBMS_RANDOM.VALUE
                    ) WHERE ROWNUM = 1;

                    INSERT INTO users (name, realname, firstname, email,
                        entities_id, user_titles_id, user_categories_id, is_active,
                        password, phone)
                    VALUES (v_login, v_nom, v_prenom,
                        v_login || '@cytech.fr', v_ent_id,
                        MOD(i-1, v_title_max)+1,
                        MOD(i-1, v_cat_max)+1,
                        CASE WHEN MOD(i,50)=0 THEN 0 ELSE 1 END,
                        'hashed_pwd_' || i,
                        '0' || TRUNC(DBMS_RANDOM.VALUE(600000000,699999999)))
                    RETURNING id INTO v_user_id;

                    -- Affecter un profil
                    INSERT INTO profiles_users (users_id, profiles_id, entities_id, is_recursive)
                    VALUES (v_user_id, MOD(i-1, v_prof_max)+1, v_ent_id,
                            CASE WHEN MOD(i,5)=0 THEN 1 ELSE 0 END);
                EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
                END;

                IF MOD(i, 100) = 0 THEN COMMIT; END IF;
            END LOOP;
            COMMIT;
            DBMS_OUTPUT.PUT_LINE(v_site || ': 500 utilisateurs crees');

            -- Affecter quelques techniciens au service IT du site avec profil recursif
            DECLARE
                v_tech_profile_id NUMBER;
                v_group_it_id NUMBER;
            BEGIN
                SELECT id INTO v_tech_profile_id
                FROM profiles
                WHERE name = 'Technicien';

                SELECT g.id INTO v_group_it_id
                FROM groups g
                WHERE g.entities_id = v_root_entity
                  AND g.name = 'Service IT ' || v_site;

                FOR rec IN (
                    SELECT u.id
                    FROM users u
                    JOIN entities e ON u.entities_id = e.id
                    WHERE e.site_code = v_site
                      AND u.is_active = 1
                      AND ROWNUM <= 10
                ) LOOP
                    BEGIN
                        INSERT INTO profiles_users (users_id, profiles_id, entities_id, is_recursive)
                        VALUES (rec.id, v_tech_profile_id, v_root_entity, 1);
                    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
                    END;

                    BEGIN
                        INSERT INTO groups_users (users_id, groups_id)
                        VALUES (rec.id, v_group_it_id);
                    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
                    END;
                END LOOP;
                COMMIT;
            END;

            -- =====================
            -- ORDINATEURS (1500 par site)
            -- =====================
            FOR i IN 1..1500 LOOP
                DECLARE
                    v_ent_id NUMBER;
                    v_loc NUMBER;
                    v_uid NUMBER;
                    v_tid NUMBER;
                    v_mid NUMBER;
                BEGIN
                    SELECT id INTO v_ent_id FROM (
                        SELECT id FROM entities WHERE site_code = v_site
                        ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
                    BEGIN
                        SELECT id INTO v_loc FROM (
                            SELECT l.id FROM locations l
                            JOIN entities e ON l.entities_id = e.id
                            WHERE e.site_code = v_site
                            ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
                    EXCEPTION WHEN NO_DATA_FOUND THEN v_loc := NULL;
                    END;
                    BEGIN
                        SELECT id INTO v_uid FROM (
                            SELECT u.id FROM users u
                            JOIN entities e ON u.entities_id = e.id
                            WHERE e.site_code = v_site
                            ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
                    EXCEPTION WHEN NO_DATA_FOUND THEN v_uid := NULL;
                    END;
                    SELECT id INTO v_tid FROM (
                        SELECT id FROM asset_types WHERE category='COMPUTER'
                        ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
                    SELECT id INTO v_mid FROM (
                        SELECT id FROM asset_models WHERE category='COMPUTER'
                        ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;

                    INSERT INTO computers (entities_id, name, serial, uuid,
                        users_id, locations_id, asset_types_id, asset_models_id,
                        manufacturers_id, states_id, networks_id)
                    VALUES (v_ent_id,
                        'PC-' || v_site || '-' || LPAD(i, 4, '0'),
                        'SN-' || v_site || '-' || LPAD(i, 5, '0'),
                        SYS_GUID(),
                        v_uid, v_loc, v_tid, v_mid,
                        MOD(i-1, v_manuf_max)+1,
                        MOD(i-1, v_state_max)+1,
                        MOD(i-1, v_net_max)+1);
                EXCEPTION WHEN OTHERS THEN NULL;
                END;
                IF MOD(i, 200) = 0 THEN COMMIT; END IF;
            END LOOP;
            COMMIT;
            DBMS_OUTPUT.PUT_LINE(v_site || ': 1500 ordinateurs crees');

            -- =====================
            -- MONITEURS (1000 par site)
            -- =====================
            FOR i IN 1..1000 LOOP
                DECLARE
                    v_ent_id NUMBER;
                    v_tid NUMBER;
                    v_mid NUMBER;
                    v_sizes t_names := t_names('21.5','24','27','32','34');
                    v_size_monitor NUMBER;
                BEGIN
                    SELECT id INTO v_ent_id FROM (
                        SELECT id FROM entities WHERE site_code = v_site
                        ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
                    SELECT id INTO v_tid FROM (
                        SELECT id FROM asset_types WHERE category='MONITOR'
                        ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
                    SELECT id INTO v_mid FROM (
                        SELECT id FROM asset_models WHERE category='MONITOR'
                        ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
                    v_size_monitor := TO_NUMBER(v_sizes(MOD(i-1, v_sizes.COUNT)+1));

                    INSERT INTO monitors (entities_id, name, serial, size_monitor,
                        asset_types_id, asset_models_id, manufacturers_id, states_id)
                    VALUES (v_ent_id,
                        'MON-' || v_site || '-' || LPAD(i, 4, '0'),
                        'SN-MON-' || v_site || '-' || LPAD(i, 5, '0'),
                        v_size_monitor,
                        v_tid, v_mid,
                        MOD(i-1, v_manuf_max)+1,
                        MOD(i-1, v_state_max)+1);
                EXCEPTION WHEN OTHERS THEN NULL;
                END;
                IF MOD(i, 200) = 0 THEN COMMIT; END IF;
            END LOOP;
            COMMIT;
            DBMS_OUTPUT.PUT_LINE(v_site || ': 1000 moniteurs crees');

            -- =====================
            -- PERIPHERIQUES (600 par site)
            -- =====================
            FOR i IN 1..600 LOOP
                DECLARE v_ent_id NUMBER; v_tid NUMBER;
                BEGIN
                    SELECT id INTO v_ent_id FROM (
                        SELECT id FROM entities WHERE site_code = v_site
                        ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
                    SELECT id INTO v_tid FROM (
                        SELECT id FROM asset_types WHERE category='PERIPHERAL'
                        ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
                    INSERT INTO peripherals (entities_id, name, serial,
                        asset_types_id, manufacturers_id, states_id)
                    VALUES (v_ent_id,
                        'PER-' || v_site || '-' || LPAD(i,4,'0'),
                        'SN-PER-' || v_site || '-' || LPAD(i,5,'0'),
                        v_tid, MOD(i-1,v_manuf_max)+1, MOD(i-1,v_state_max)+1);
                EXCEPTION WHEN OTHERS THEN NULL;
                END;
                IF MOD(i,200)=0 THEN COMMIT; END IF;
            END LOOP;
            COMMIT;
            DBMS_OUTPUT.PUT_LINE(v_site || ': 600 peripheriques crees');

            -- =====================
            -- IMPRIMANTES (80 par site)
            -- =====================
            FOR i IN 1..80 LOOP
                DECLARE v_ent_id NUMBER; v_tid NUMBER;
                BEGIN
                    SELECT id INTO v_ent_id FROM (
                        SELECT id FROM entities WHERE site_code = v_site
                        ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
                    SELECT id INTO v_tid FROM (
                        SELECT id FROM asset_types WHERE category='PRINTER'
                        ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
                    INSERT INTO printers (entities_id, name, serial,
                        asset_types_id, manufacturers_id, states_id, networks_id)
                    VALUES (v_ent_id,
                        'PRT-' || v_site || '-' || LPAD(i,3,'0'),
                        'SN-PRT-' || v_site || '-' || LPAD(i,5,'0'),
                        v_tid, MOD(i-1,v_manuf_max)+1, MOD(i-1,v_state_max)+1,
                        MOD(i-1,v_net_max)+1);
                EXCEPTION WHEN OTHERS THEN NULL;
                END;
            END LOOP;
            COMMIT;
            DBMS_OUTPUT.PUT_LINE(v_site || ': 80 imprimantes crees');

            -- =====================
            -- TELEPHONES (200 par site)
            -- =====================
            FOR i IN 1..200 LOOP
                DECLARE v_ent_id NUMBER; v_tid NUMBER;
                BEGIN
                    SELECT id INTO v_ent_id FROM (
                        SELECT id FROM entities WHERE site_code = v_site
                        ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
                    SELECT id INTO v_tid FROM (
                        SELECT id FROM asset_types WHERE category='PHONE'
                        ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
                    INSERT INTO phones (entities_id, name, serial,
                        asset_types_id, manufacturers_id, states_id)
                    VALUES (v_ent_id,
                        'TEL-' || v_site || '-' || LPAD(i,3,'0'),
                        'SN-TEL-' || v_site || '-' || LPAD(i,5,'0'),
                        v_tid, MOD(i-1,v_manuf_max)+1, MOD(i-1,v_state_max)+1);
                EXCEPTION WHEN OTHERS THEN NULL;
                END;
            END LOOP;
            COMMIT;
            DBMS_OUTPUT.PUT_LINE(v_site || ': 200 telephones crees');

            -- =====================
            -- EQUIPEMENTS RESEAU (40 par site)
            -- =====================
            FOR i IN 1..40 LOOP
                DECLARE v_ent_id NUMBER; v_tid NUMBER; v_amid NUMBER;
                BEGIN
                    SELECT id INTO v_ent_id FROM (
                        SELECT id FROM entities WHERE site_code = v_site
                        ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
                    SELECT id INTO v_tid FROM (
                        SELECT id FROM asset_types WHERE category='NETWORK_EQUIPMENT'
                        ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
                    SELECT id INTO v_amid FROM (
                        SELECT id FROM asset_models WHERE category='NETWORK_EQUIPMENT'
                        ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
                    INSERT INTO network_equipments (entities_id, name, serial, ram,
                        asset_types_id, asset_models_id, manufacturers_id, states_id, networks_id)
                    VALUES (v_ent_id,
                        'NET-' || v_site || '-' || LPAD(i,3,'0'),
                        'SN-NET-' || v_site || '-' || LPAD(i,5,'0'),
                        CASE MOD(i,3) WHEN 0 THEN 4096 WHEN 1 THEN 8192 ELSE 16384 END,
                        v_tid, v_amid,
                        MOD(i-1,v_manuf_max)+1, MOD(i-1,v_state_max)+1,
                        MOD(i-1,v_net_max)+1);
                EXCEPTION WHEN OTHERS THEN NULL;
                END;
            END LOOP;
            COMMIT;
            DBMS_OUTPUT.PUT_LINE(v_site || ': 40 equipements reseau crees');

            -- =====================
            -- TICKETS SUPPORT (120 par site)
            -- =====================
            FOR i IN 1..120 LOOP
                DECLARE
                    v_ent_id NUMBER;
                    v_asset_id NUMBER;
                    v_requester_id NUMBER;
                    v_group_id NUMBER;
                    v_cat_id NUMBER;
                    v_ticket_id NUMBER;
                    v_tech_id NUMBER;
                    v_status VARCHAR2(30);
                    v_priority VARCHAR2(20);
                BEGIN
                    IF MOD(i, 4) = 0 THEN
                        SELECT pr.id, pr.entities_id INTO v_asset_id, v_ent_id
                        FROM (
                            SELECT pr.id, pr.entities_id
                            FROM printers pr
                            JOIN entities e ON pr.entities_id = e.id
                            WHERE e.site_code = v_site
                            ORDER BY DBMS_RANDOM.VALUE
                        ) pr
                        WHERE ROWNUM = 1;
                    ELSE
                        SELECT c.id, c.entities_id INTO v_asset_id, v_ent_id
                        FROM (
                            SELECT c.id, c.entities_id
                            FROM computers c
                            JOIN entities e ON c.entities_id = e.id
                            WHERE e.site_code = v_site
                            ORDER BY DBMS_RANDOM.VALUE
                        ) c
                        WHERE ROWNUM = 1;
                    END IF;

                    SELECT u.id INTO v_requester_id
                    FROM (
                        SELECT u.id
                        FROM users u
                        JOIN entities e ON u.entities_id = e.id
                        WHERE e.site_code = v_site AND u.is_active = 1
                        ORDER BY DBMS_RANDOM.VALUE
                    ) u
                    WHERE ROWNUM = 1;

                    SELECT g.id INTO v_group_id
                    FROM groups g
                    JOIN entities e ON g.entities_id = e.id
                    WHERE e.site_code = v_site AND g.name = 'Service IT ' || v_site
                    AND ROWNUM = 1;

                    SELECT id INTO v_cat_id
                    FROM (
                        SELECT id FROM ticket_categories
                        ORDER BY DBMS_RANDOM.VALUE
                    )
                    WHERE ROWNUM = 1;

                    SELECT u.id INTO v_tech_id
                    FROM (
                        SELECT u.id
                        FROM users u
                            JOIN profiles_users pu ON u.id = pu.users_id
                            JOIN profiles p ON pu.profiles_id = p.id
                        WHERE p.name = 'Technicien'
                          AND pu.is_recursive = 1
                          AND pu.entities_id = (
                              SELECT id FROM entities
                              WHERE site_code = v_site AND hier_level = 1
                              AND ROWNUM = 1
                          )
                        ORDER BY DBMS_RANDOM.VALUE
                    ) u
                    WHERE ROWNUM = 1;

                    v_status := CASE MOD(i, 6)
                        WHEN 0 THEN 'NOUVEAU'
                        WHEN 1 THEN 'ASSIGNE'
                        WHEN 2 THEN 'EN_COURS'
                        WHEN 3 THEN 'EN_ATTENTE'
                        WHEN 4 THEN 'RESOLU'
                        ELSE 'CLOS'
                    END;

                    v_priority := CASE MOD(i, 4)
                        WHEN 0 THEN 'BASSE'
                        WHEN 1 THEN 'MOYENNE'
                        WHEN 2 THEN 'HAUTE'
                        ELSE 'CRITIQUE'
                    END;

                    IF MOD(i, 4) = 0 THEN
                        INSERT INTO tickets (entities_id, title, description,
                            status, priority, requester_users_id,
                            assigned_groups_id, ticket_categories_id, printers_id,
                            date_assigned, date_resolved, date_closed)
                        VALUES (v_ent_id,
                            'Incident imprimante ' || v_site || ' #' || i,
                            'Probleme signale sur une imprimante du site ' || v_site,
                            v_status, v_priority, v_requester_id,
                            v_group_id, v_cat_id, v_asset_id,
                            CASE WHEN v_status != 'NOUVEAU' THEN SYSTIMESTAMP ELSE NULL END,
                            CASE WHEN v_status IN ('RESOLU','CLOS') THEN SYSTIMESTAMP ELSE NULL END,
                            CASE WHEN v_status = 'CLOS' THEN SYSTIMESTAMP ELSE NULL END)
                        RETURNING id INTO v_ticket_id;
                    ELSE
                        INSERT INTO tickets (entities_id, title, description,
                            status, priority, requester_users_id,
                            assigned_groups_id, ticket_categories_id, computers_id,
                            date_assigned, date_resolved, date_closed)
                        VALUES (v_ent_id,
                            'Incident ordinateur ' || v_site || ' #' || i,
                            'Probleme signale sur un ordinateur du site ' || v_site,
                            v_status, v_priority, v_requester_id,
                            v_group_id, v_cat_id, v_asset_id,
                            CASE WHEN v_status != 'NOUVEAU' THEN SYSTIMESTAMP ELSE NULL END,
                            CASE WHEN v_status IN ('RESOLU','CLOS') THEN SYSTIMESTAMP ELSE NULL END,
                            CASE WHEN v_status = 'CLOS' THEN SYSTIMESTAMP ELSE NULL END)
                        RETURNING id INTO v_ticket_id;
                    END IF;

                    IF v_status != 'NOUVEAU' THEN
                        INSERT INTO ticket_users (tickets_id, users_id, assigned_by)
                        VALUES (v_ticket_id, v_tech_id, v_requester_id);
                    END IF;
                EXCEPTION WHEN OTHERS THEN NULL;
                END;
                IF MOD(i, 40) = 0 THEN COMMIT; END IF;
            END LOOP;
            COMMIT;
            DBMS_OUTPUT.PUT_LINE(v_site || ': 120 tickets support crees');

            -- =====================
            -- VLANs (10 par site)
            -- =====================
            FOR i IN 1..v_vlan_names.COUNT LOOP
                DECLARE
                    v_ent_id NUMBER;
                    v_vlan_name VARCHAR2(100) := v_vlan_names(i);
                BEGIN
                    SELECT id INTO v_ent_id FROM (
                        SELECT id FROM entities WHERE site_code = v_site AND hier_level = 1
                        ORDER BY id) WHERE ROWNUM = 1;
                    INSERT INTO vlans (entities_id, name, tag)
                    VALUES (v_ent_id, v_vlan_name || '-' || v_site, i * 10);
                EXCEPTION WHEN OTHERS THEN NULL;
                END;
            END LOOP;
            COMMIT;

            -- =====================
            -- PORTS RESEAU (2 par ordinateur, 24 par equip reseau)
            -- =====================
            v_counter := 0;
            FOR rec IN (SELECT c.id, c.entities_id FROM computers c
                        JOIN entities e ON c.entities_id = e.id
                        WHERE e.site_code = v_site AND ROWNUM <= 1500) LOOP
                FOR p IN 1..2 LOOP
                    BEGIN
                        INSERT INTO network_ports (entities_id, name, mac,
                            instantiation_type, logical_number, computers_id)
                        VALUES (rec.entities_id,
                            'eth' || (p-1),
                            SUBSTR(RAWTOHEX(SYS_GUID()),1,2) || ':' ||
                            SUBSTR(RAWTOHEX(SYS_GUID()),3,2) || ':' ||
                            SUBSTR(RAWTOHEX(SYS_GUID()),5,2) || ':' ||
                            SUBSTR(RAWTOHEX(SYS_GUID()),7,2) || ':' ||
                            SUBSTR(RAWTOHEX(SYS_GUID()),9,2) || ':' ||
                            SUBSTR(RAWTOHEX(SYS_GUID()),11,2),
                            'Ethernet', p-1, rec.id);
                        v_counter := v_counter + 1;
                    EXCEPTION WHEN OTHERS THEN NULL;
                    END;
                END LOOP;
                IF MOD(v_counter, 500) = 0 THEN COMMIT; END IF;
            END LOOP;
            COMMIT;

            FOR rec IN (SELECT ne.id, ne.entities_id FROM network_equipments ne
                        JOIN entities e ON ne.entities_id = e.id
                        WHERE e.site_code = v_site) LOOP
                FOR p IN 1..24 LOOP
                    BEGIN
                        INSERT INTO network_ports (entities_id, name,
                            instantiation_type, logical_number, network_equipments_id)
                        VALUES (rec.entities_id,
                            'GigabitEthernet0/' || p,
                            'Ethernet', p, rec.id);
                        v_counter := v_counter + 1;
                    EXCEPTION WHEN OTHERS THEN NULL;
                    END;
                END LOOP;
            END LOOP;
            COMMIT;
            DBMS_OUTPUT.PUT_LINE(v_site || ': ' || v_counter || ' ports reseau crees');

        END;
    END LOOP;

    -- =====================
    -- STATISTIQUES FINALES
    -- =====================
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('=== STATISTIQUES FINALES ===');
    FOR rec IN (
        SELECT 'entities' AS t, COUNT(*) AS c FROM entities UNION ALL
        SELECT 'locations', COUNT(*) FROM locations UNION ALL
        SELECT 'users', COUNT(*) FROM users UNION ALL
        SELECT 'groups', COUNT(*) FROM groups UNION ALL
        SELECT 'computers', COUNT(*) FROM computers UNION ALL
        SELECT 'monitors', COUNT(*) FROM monitors UNION ALL
        SELECT 'peripherals', COUNT(*) FROM peripherals UNION ALL
        SELECT 'printers', COUNT(*) FROM printers UNION ALL
        SELECT 'phones', COUNT(*) FROM phones UNION ALL
        SELECT 'network_equipments', COUNT(*) FROM network_equipments UNION ALL
        SELECT 'tickets', COUNT(*) FROM tickets UNION ALL
        SELECT 'network_ports', COUNT(*) FROM network_ports UNION ALL
        SELECT 'vlans', COUNT(*) FROM vlans
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(RPAD(rec.t, 25) || ': ' || rec.c);
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('=== FIN GENERATION ===');
END SP_GENERER_JEU_DE_TEST;
/

-- Execution :
-- SET SERVEROUTPUT ON SIZE UNLIMITED
-- EXEC SP_GENERER_JEU_DE_TEST;
